language: go
go:
  - 1.7.5

env:
  global:
    - KAFKA_PEERS=localhost:9091,localhost:9092,localhost:9093,localhost:9094,localhost:9095
    - ZOOKEEPER_PEERS=localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185
    - KAFKA_INSTALL_ROOT=/home/travis/kafka
    - KAFKA_HOSTNAME=localhost
    - DEBUG=true
  matrix:
#    - KAFKA_VERSION=0.8.2.2
#    - KAFKA_VERSION=0.9.0.1
    - KAFKA_VERSION=0.10.1.0

before_install:
  - export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}/vendor/github.com/Shopify/sarama
  - vendor/github.com/Shopify/sarama/vagrant/install_cluster.sh
  - vendor/github.com/Shopify/sarama/vagrant/boot_cluster.sh
  - vendor/github.com/Shopify/sarama/vagrant/create_topics.sh

script: ./scripts/travis_build.sh
sudo: false
